[package]
name = "elz"
version = "0.1.0"
authors = ["dannypsnl <dannypsnl@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
thiserror = "1.0.6"
strum = "0.16.0"
strum_macros = "0.16.0"
walkdir = "2.2.9"
rust-embed = "5.2.0"
codespan = "0.8.0"
codespan-reporting = "0.8.0"
